app: pretrain_va_lejepa
folder: OUTPUT/pretrain_va_lejepa/I3-C1
meta:
  seed: 0
  dtype: bfloat16
  auto_resume: true
  read_checkpoint: null
  log_every_steps: 50
  save_every_steps: 5000
ema:
  enabled: true
  decay: 0.9999
  update_every: 32
  device: cpu
yamls:
  data: CONFIGS/datas/va_lejepa/va-global6s-local2s.yaml
  model: CONFIGS/models/va_lejepa-vitl-emotion2vec.yaml
  opt: CONFIGS/opt/va_lejepa.yaml
  loss: CONFIGS/mask_loss/va_lejepa.yaml
model:
  video:
    init_source: video_lejepa
  audio:
    init_source: audio_lejepa
