# 3_CMDC_LA.csv :: HAMD :: regression
data:
  datasets:
    - /home/data/sdc/FAVOR/DATASET/splits-0901/3_CMDC_LA.csv
  rootpaths:
    - /home/data/sdb/基座模型数据集/3心理数据集/CMDC/
  task: regression
  label_column: HAMD
