# 2_EMNS_SA.csv :: intensity :: regression
data:
  datasets:
    - /home/data/sdc/FAVOR/DATASET/splits-0901/2_EMNS_SA.csv
  rootpaths:
    - /home/data/sdb/基座模型数据集/2情绪数据集/EMNS/
  task: regression
  label_column: intensity
