# 2_EMOVIE_SA.csv :: pos_intensity :: regression
data:
  datasets:
    - DATASET/splits-0901/2_EMOVIE_SA.csv
  rootpaths:
    - /home/data/sdb/基座模型数据集/2情绪数据集/EMOVIE/
  task: regression
  label_column: pos_intensity
