# 2_CREMA-D_SV.csv :: emotion :: classification (6 classes)
data:
  datasets:
  - /home/data/sdc/FAVOR/DATASET/splits-0901/2_CREMA-D_SV.csv
  datasets_weights:
  - 1
  rootpaths:
  - /home/data/sdb/基座模型数据集/2情绪数据集/CREMA-D/
  task: classification
  num_class: 6
  # Column containing integer class labels or floating-point regression targets.
  label_column: emotion
