# 2_EmotionTalk_SV.csv :: emotion :: classification (7 classes)
data:
  datasets:
  - DATASET/splits-0901/2_EmotionTalk_SV.csv
  datasets_weights:
  - 1
  rootpaths:
  - /home/data/sdb/基座模型数据集/2情绪数据集/EmotionTalk/
  task: classification
  num_class: 7
  # Column containing integer class labels or floating-point regression targets.
  label_column: emotion
