# 2_MER242526_SV.csv :: emotion :: classification (6 classes)
data:
  datasets:
  - /home/data/sdc/FAVOR/DATASET/splits-0901/2_MER242526_SV.csv
  datasets_weights:
  - 1
  rootpaths:
  - /home/data/sdc/MER/
  task: classification
  num_class: 6
  # Column containing integer class labels or floating-point regression targets.
  label_column: emotion
