app: pretrain_va_lejepa
folder: OUTPUT/pretrain_va_lejepa/I0-C1
meta:
  seed: 0
  dtype: bfloat16
  auto_resume: true
  read_checkpoint: null
  log_every_steps: 50
  save_every_steps: 5000
ema:
  enabled: true
  decay: 0.9999
  update_every: 32
  device: cpu
yamls:
  data: CONFIGS/data/pretrain/audio-video/lejepa/va-global6s-local2s.yaml
  model: CONFIGS/models/pretrain/audio-video/lejepa/vitl-emotion2vec.yaml
  opt: CONFIGS/optimization/pretrain/audio-video/lejepa/steps100000-warmup10000.yaml
  loss: CONFIGS/losses/audio-video-lejepa.yaml
model:
  video:
    init_source: vjepa
  audio:
    init_source: emotion2vec
