app: finetune_v
folder: /home/data/sdc/FAVOR/OUTPUT/finetune_v/vitl16/RAVDESS-emotion/reproduce-favor-e5-23out/
meta:
  dtype: bfloat16
  eval_freq: 1
  load_checkpoint: true
  read_checkpoint: /home/data/sdc/FAVOR/OUTPUT/pretrain_v/vitl16/FaVoR-112px-48f/e5.pt
  reset_epoch: true
  save_every_freq: 10
  seed: 239
yamls:
  data: /home/data/sdc/FAVOR/CONFIGS/datas/vfinetune-RAVDESS-emotion-reproduce.yaml
  opt: /home/data/sdc/FAVOR/CONFIGS/opt/vfinetune-opt-ravdess-reproduce.yaml
  model: /home/data/sdc/FAVOR/CONFIGS/models/vfinetune-vit-l-reproduce.yaml
