app: finetune_v
folder: OUTPUT/finetune_v/vitl16/RAVDESS-emotion/FaVoR-112px-48f-8fps-e5/
meta:
  dtype: bfloat16
  eval_freq: 1
  load_checkpoint: true
  read_checkpoint: OUTPUT/pretrain_v/vitl16/FaVoR-112px-48f/e5.pt
  reset_epoch: true
  save_every_freq: 100
  seed: 239
  # frozen_encoder: true
yamls:
  data: CONFIGS/datas/vfinetune/cls/RAVDESS-emotion-cls8.yaml
  sampling: CONFIGS/datas/vfinetune/48-8.yaml
  opt: CONFIGS/opt/vfinetune-opt-80-5-5e-5.yaml
  model: CONFIGS/models/vfinetune-vit-l-4layer.yaml
