app: pretrain_v
folder: /home/data/sdc/FAVOR/OUTPUT/pretrain_v/vitl16/FaVoR-112px-48f-cooldown/
meta:
  dtype: bfloat16
  eval_freq: 1
  load_checkpoint: true
  read_checkpoint: /home/data/sdc/FAVOR/OUTPUT/pretrain_v/vitl16/FaVoR-112px-48f/latest.pt
  reset_epoch: false
  save_every_freq: 5
  seed: 239
yamls:
  data: /home/data/sdc/FAVOR/CONFIGS/datas/vpretrain/vpretrain-data-cooldown.yaml
  opt: /home/data/sdc/FAVOR/CONFIGS/opt/vpretrain-opt-cooldown.yaml
  model: /home/data/sdc/FAVOR/CONFIGS/models/vpretrain-vit-l.yaml
  mask: /home/data/sdc/FAVOR/CONFIGS/mask_loss/vjepa-pretrain.yaml
