app: finetune_v
folder: /home/data/sdc/FAVOR/OUTPUT/finetune_v/vitl16/FaVoR-112px-48f-8fps-e5/IEMOCAP-dominance/
meta:
  dtype: bfloat16
  eval_freq: 1
  load_checkpoint: true
  read_checkpoint: /home/data/sdc/FAVOR/OUTPUT/pretrain_v/vitl16/FaVoR-112px-48f/e5.pt
  reset_epoch: true
  save_every_freq: 10
  seed: 239
  # frozen_encoder: true
data:
  fps: 8
yamls:
  data: /home/data/sdc/FAVOR/CONFIGS/datas/vfinetune-IEMOCAP-dominance-reg.yaml
  opt: /home/data/sdc/FAVOR/CONFIGS/opt/vfinetune-opt-80-5-5e-5.yaml
  model: /home/data/sdc/FAVOR/CONFIGS/models/vfinetune-vit-l-4layer.yaml
