app: finetune_a
folder: OUTPUT/finetune_a/aemojepa-plus-large/MER242526-pos_intensity/jepa-280k
meta:
  dtype: bfloat16
  load_checkpoint: true
  read_checkpoint: OUTPUT/pretrain_a/emotion_jepa_full_dataset/checkpoint_final.pt
  reset_epoch: true
  seed: 239
  frozen_encoder: false
  min_load_ratio: 0.95
yamls:
  data: CONFIGS/datas/afinetune/reg/MER242526-pos_intensity-reg.yaml
  sampling: CONFIGS/datas/afinetune/audio-4s-4clips.yaml
  opt: CONFIGS/opt/afinetune-opt-30.yaml
  model: CONFIGS/models/afinetune-aemojepa-plus-large.yaml
