app: finetune_v
folder: OUTPUT/finetune_v/vitl16/MER242526-emotion/favor-e11-23out-newnewopt/
meta:
  dtype: bfloat16
  eval_freq: 1
  load_checkpoint: true
  # read_checkpoint: OUTPUT/pretrain_v/vitl16/videos_all/e35.pt
  read_checkpoint: OUTPUT/pretrain_v/vitl16/FaVoR-112px-48f/latest.pt
  reset_epoch: true
  save_every_freq: 100
  seed: 239
  # frozen_encoder: true
yamls:
  data: CONFIGS/data/finetune/video/classification/MER242526-emotion.yaml
  sampling: CONFIGS/data/finetune/video/sampling/48frames-4fps.yaml
  opt: CONFIGS/optimization/finetune/video/epochs80-warmup5-lr5e-05.yaml
  model: CONFIGS/models/finetune/video/vit-l.yaml
