app: finetune_v
folder: OUTPUT/finetune_v/vitl16/MER242526-emotion/favor-e5-4layer-data64-16-newopt
meta:
  dtype: bfloat16
  eval_freq: 1
  load_checkpoint: true
  # read_checkpoint: OUTPUT/pretrain_v/vitl16/videos_all/e35.pt
  read_checkpoint: OUTPUT/pretrain_v/vitl16/FaVoR-112px-48f/e5.pt
  reset_epoch: true
  save_every_freq: 100
  seed: 239
yamls:
  # data: CONFIGS/data/finetune/video-MER242526-emotion-cls6.yaml
  data: CONFIGS/data/finetune/video/classification/MER242526-emotion.yaml
  sampling: CONFIGS/data/finetune/video/sampling/64frames-16fps.yaml
  opt: CONFIGS/optimization/finetune/video/epochs80-warmup10-lr0.0004.yaml
  model: CONFIGS/models/finetune/video/vit-l-4layers.yaml
