app: finetune_v
folder: /home/data/sdc/FAVOR/OUTPUT/testttt/
meta:
  dtype: bfloat16
  eval_freq: 1
  load_checkpoint: true
  # read_checkpoint: /home/data/sdc/vjepa2/outputs/videos_all/e35.pt
  read_checkpoint: /home/data/sdc/FAVOR/OUTPUT/pretrain_v/vitl16/FaVoR-112px-48f/latest.pt
  reset_epoch: true
  save_every_freq: 10
  seed: 239
  # frozen_encoder: true
yamls:
  data: /home/data/sdc/FAVOR/CONFIGS/datas/vfinetune-MER242526-emotion-cls6.yaml
  opt: /home/data/sdc/FAVOR/CONFIGS/opt/vfinetune-opt-80-5-5e-5.yaml
  model: /home/data/sdc/FAVOR/CONFIGS/models/vfinetune-vit-l.yaml
