app: finetune_v
folder: /home/data/sdc/FAVOR/OUTPUT/finetune_v/vitl16/FaVoR-112px-48f/CREMA-D-emotion/
meta:
  dtype: bfloat16
  eval_freq: 1
  load_checkpoint: true
  read_checkpoint: /home/data/sdc/FAVOR/OUTPUT/pretrain_v/vitl16/FaVoR-112px-48f/latest.pt
  reset_epoch: true
  save_every_freq: 10
  seed: 239
  # frozen_encoder: true
yamls:
  data: /home/data/sdc/FAVOR/CONFIGS/datas/vfinetune-CREMA-D-emotion-cls6.yaml
  opt: /home/data/sdc/FAVOR/CONFIGS/opt/vfinetune-opt-250-40.yaml
  model: /home/data/sdc/FAVOR/CONFIGS/models/vfinetune-vit-l.yaml
