# 2_MER242526_SV.csv :: 26openset :: multi_label_classification
data:
  datasets:
    - /home/data/sdc/FAVOR/DATASET/splits-0901/2_MER242526_SV.csv
  rootpaths:
    - /home/data/sdc/MER/
  task: multi_label_classification
  num_class: 23
  label_column: 26openset
