model:
  video:
    name: vit_large
    patch_size: 16
    tubelet_size: 1
    token_drop_rate: 0.0
    attn_mode: block_causal
    use_rope: true
    use_sdpa: true
    use_activation_checkpointing: true
    init_source: video_lejepa
    weight_source: encoder
    vjepa_checkpoint: CKPT/vjepa2/vitl.pt
    video_lejepa_checkpoint: OUTPUT/pretrain_v_lejepa/vitl16/FaVoR-112px-48f8/e25.pt
  audio:
    backbone:
      mode: emotion2vec
      conv_pos_depth: 5
      conv_pos_width: 95
      conv_pos_groups: 16
      prenet_depth: 4
      num_extra_tokens: 10
      learned_alibi_scale: false
    extractor:
      conv_layers:
      - - 512
        - 10
        - 5
      - - 512
        - 3
        - 2
      - - 512
        - 3
        - 2
      - - 512
        - 3
        - 2
      - - 512
        - 3
        - 2
      - - 512
        - 2
        - 2
      - - 512
        - 2
        - 2
      mode: layer_norm
      conv_bias: false
      dropout: 0.0
    encoder:
      depth: 8
      d_model: 1024
      nhead: 16
      dim_feedforward: 4096
      dropout: 0.0
      attention_dropout: 0.0
      activation_dropout: 0.0
      post_mlp_dropout: 0.0
      qkv_bias: true
      layer_norm_first: false
      norm_eps: 1.0e-06
      ffn_targets: true
    pooling:
      type: extra_token
      index: 0
    init_source: audio_lejepa
    weight_source: encoder
    emotion2vec_checkpoint: CKPT/emotion2vec_plus_large/model.pt
    audio_lejepa_checkpoint: OUTPUT/pretrain_a_lejepa/emotion2vec-plus-large/FaVoR-4s-local2s/latest.pt
  audio_gradient_checkpointing: true
  fusion:
    enabled:
    - feature
    bridge: concat_transformer
    common_dim: 768
    projection_dim: 256
    projector_hidden_dim: 2048
    modality_embedding: true
    temporal_embedding: sincos
    fuse_token: true
    input_adapter:
      hidden_dim: 1536
    early:
      depth: 4
      nhead: 12
      max_video_tokens_per_time: 16
      max_audio_tokens_per_time: 4
      loss_weight: 1.0
      gradient_checkpointing: true
    feature:
      depth: 4
      nhead: 12
      loss_weight: 1.0
      gradient_checkpointing: true
    late:
      depth: 2
      nhead: 12
      loss_weight: 1.0
      gradient_checkpointing: true
