app: finetune_a
folder: OUTPUT/finetune_a/emotion2vec-plus-large/IEMOCAP-emotion-drop03
meta:
  dtype: bfloat16
  load_checkpoint: true
  read_checkpoint: CKPT/emotion2vec_plus_large/model.pt
  reset_epoch: true
  seed: 239
  frozen_encoder: false
  min_load_ratio: 0.95
model:
  backbone:
    prenet_dropout: 0.2
  extractor:
    dropout: 0.2
  encoder:
    dropout_input: 0.2
    dropout: 0.2
    attention_dropout: 0.2
    activation_dropout: 0.2
    post_mlp_dropout: 0.2
  head:
    attention_dropout: 0.2
    dropout: 0.2
optimization:
  grokfast: true
  grokfast_alpha: 0.98
  grokfast_lambda: 2.0
yamls:
  data: CONFIGS/datas/afinetune/cls/IEMOCAP-emotion-cls9.yaml
  sampling: CONFIGS/datas/afinetune/audio-4s-4clips.yaml
  opt: CONFIGS/opt/afinetune-opt-30.yaml
  model: CONFIGS/models/afinetune-emotion2vec-plus-large.yaml
