app: pretrain_audio_lejepa
folder: OUTPUT/pretrain_audio_lejepa/emotion2vec-plus-large/A3-6s-local2s
yamls:
  data: CONFIGS/datas/audio_lejepa/pretrain.yaml
  opt: CONFIGS/opt/audio_lejepa.yaml
  model: CONFIGS/models/audio_lejepa-emotion2vec-plus-large.yaml
  loss: CONFIGS/mask_loss/audio_lejepa.yaml
  ablation: CONFIGS/datas/audio_lejepa/a3-6s-local2s.yaml
meta:
  dtype: bfloat16
  seed: 42
  read_checkpoint: null
  auto_resume: true
  save_every_steps: 5000
  log_every_steps: 50

