app: pretrain_a
folder: /home/data/sdc/FAVOR/OUTPUT/pretrain_a/aemojepa-plus-large/FaVoR-2to4s
meta:
  dtype: bfloat16
  seed: 42
  init_checkpoint: /home/data/sdc/lxc/audio-pretrain/AEmo-JEPA/pretrained/emotion2vec_plus_large/model.pt
  read_checkpoint: null
  auto_resume: true
  save_every_steps: 5000
  log_every_steps: 50
yamls:
  data: /home/data/sdc/FAVOR/CONFIGS/datas/apretrain/apretrain-data.yaml
  opt: /home/data/sdc/FAVOR/CONFIGS/opt/apretrain-opt-100k.yaml
  model: /home/data/sdc/FAVOR/CONFIGS/models/apretrain-aemojepa-plus-large.yaml
  mask: /home/data/sdc/FAVOR/CONFIGS/mask_loss/ajepa-pretrain.yaml
