app: pretrain_a
folder: OUTPUT/pretrain_a/aemojepa-plus-large/FaVoR-2to4s
meta:
  dtype: bfloat16
  seed: 42
  init_checkpoint: CKPT/emotion2vec_plus_large/model.pt
  read_checkpoint: null
  auto_resume: true
  save_every_steps: 5000
  log_every_steps: 50
yamls:
  data: CONFIGS/datas/apretrain/apretrain-data.yaml
  opt: CONFIGS/opt/apretrain-opt-100k.yaml
  model: CONFIGS/models/apretrain-aemojepa-plus-large.yaml
  mask: CONFIGS/mask_loss/ajepa-pretrain.yaml
