# 3_Androids-Corpus_LA.csv :: label :: classification
data:
  datasets:
    - DATASET/splits-0901/3_Androids-Corpus_LA.csv
  rootpaths:
    - /home/data/sdb/基座模型数据集/3心理数据集/Androids-Corpus/
  task: classification
  num_class: 2
  label_column: label
