# 2_EMNS_SA.csv :: emotion :: classification
data:
  datasets:
    - /home/data/sdc/FAVOR/DATASET/splits-0901/2_EMNS_SA.csv
  rootpaths:
    - /home/data/sdb/基座模型数据集/2情绪数据集/EMNS/
  task: classification
  num_class: 8
  label_column: emotion
