# 2_IEMOCAP_SV.csv :: emotion :: classification
data:
  datasets:
    - DATASET/splits-0901/2_IEMOCAP_SV.csv
  rootpaths:
    - /home/data/sdb/基座模型数据集/2情绪数据集/IEMOCAP/
  task: classification
  num_class: 9
  label_column: emotion
