# 2_MER2023_SV.csv :: emotion :: classification
data:
  datasets:
    - /home/data/sdc/FAVOR/DATASET/splits-0901/2_MER2023_SV.csv
  rootpaths:
    - /home/data/sdc/MER/MER2023/
  task: classification
  num_class: 6
  label_column: emotion
