# 3_MODMA_SA.csv :: label :: classification
data:
  datasets:
    - /home/data/sdc/FAVOR/DATASET/splits-0901/3_MODMA_SA.csv
  rootpaths:
    - /home/data/sdb/基座模型数据集/3心理数据集/MODMA/
  task: classification
  num_class: 2
  label_column: label
