# 2_MER2023_SV.csv :: pos_intensity :: regression (range 0.0~9.25)
data:
  datasets:
  - /home/data/sdc/FAVOR/DATASET/splits-0901/2_MER2023_SV.csv
  datasets_weights:
  - 1
  rootpaths:
  - /home/data/sdc/MER/MER2023/
  task: regression
  # Column containing integer class labels or floating-point regression targets.
  label_column: pos_intensity
